# Generated by Django 6.1 on 2026-08-28 15:41

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='タグ名')),
                ('color', models.CharField(default='#64748b', max_length=7, verbose_name='色')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='会社名')),
                ('name_kana', models.CharField(blank=True, max_length=120, verbose_name='会社名カナ')),
                ('industry', models.CharField(choices=[('it', 'IT・ソフトウェア'), ('manufacturing', '製造'), ('retail', '小売・流通'), ('finance', '金融'), ('medical', '医療・ヘルスケア'), ('construction', '建設・不動産'), ('other', 'その他')], default='other', max_length=20, verbose_name='業種')),
                ('rank', models.CharField(choices=[('a', 'A（重要顧客）'), ('b', 'B（通常）'), ('c', 'C（見込み薄）')], default='b', max_length=1, verbose_name='ランク')),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='従業員数')),
                ('website', models.URLField(blank=True, verbose_name='Web サイト')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='代表電話')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='住所')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
            ],
            options={
                'verbose_name': '取引先',
                'verbose_name_plural': '取引先',
                'ordering': ['name_kana', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('last_name', models.CharField(max_length=40, verbose_name='姓')),
                ('first_name', models.CharField(blank=True, max_length=40, verbose_name='名')),
                ('kana', models.CharField(blank=True, max_length=80, verbose_name='フリガナ')),
                ('title', models.CharField(blank=True, max_length=60, verbose_name='役職')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メール')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主担当')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.company', verbose_name='取引先')),
                ('tags', models.ManyToManyField(blank=True, related_name='contacts', to='crm.tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': '担当者',
                'verbose_name_plural': '担当者',
                'ordering': ['company__name', '-is_primary', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('title', models.CharField(max_length=120, verbose_name='案件名')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='金額')),
                ('stage', models.CharField(choices=[('lead', 'リード'), ('qualified', '案件化'), ('proposal', '提案中'), ('negotiation', '交渉中'), ('won', '受注'), ('lost', '失注')], db_index=True, default='lead', max_length=20, verbose_name='ステージ')),
                ('probability', models.PositiveSmallIntegerField(default=10, verbose_name='確度(%)')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='受注予定日')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('description', models.TextField(blank=True, verbose_name='概要')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.company', verbose_name='取引先')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.contact', verbose_name='担当者')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to=settings.AUTH_USER_MODEL, verbose_name='営業担当')),
            ],
            options={
                'verbose_name': '商談',
                'verbose_name_plural': '商談',
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('kind', models.CharField(choices=[('call', '電話'), ('email', 'メール'), ('meeting', '打合せ'), ('note', 'メモ')], default='note', max_length=20, verbose_name='種別')),
                ('subject', models.CharField(max_length=150, verbose_name='件名')),
                ('body', models.TextField(blank=True, verbose_name='内容')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='実施日時')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.company', verbose_name='取引先')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.contact', verbose_name='担当者')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.deal', verbose_name='商談')),
            ],
            options={
                'verbose_name': '活動履歴',
                'verbose_name_plural': '活動履歴',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('title', models.CharField(max_length=150, verbose_name='タイトル')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('is_done', models.BooleanField(default=False, verbose_name='完了')),
                ('priority', models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], default=2, verbose_name='優先度')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='担当')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.deal', verbose_name='関連商談')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク',
                'ordering': ['is_done', 'due_date', '-priority'],
            },
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='company_name_unique_ci'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('probability__lte', 100)), name='deal_probability_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='deal_amount_gte_0'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['-occurred_at'], name='crm_activit_occurre_081436_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='crm_contact_email_240305_idx'),
        ),
    ]
